requirement fixes for gensim
Upgrades results in problem with gensim/scipy
ImportError: cannot import name 'triu' from 'scipy.linalg'
AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Downgrading scipy and fixing gensim version